### ISSUE TITLE
Customer object has no attribute 'select'

### ISSUE THREAD

**Issue by rtruxal** [elementsinteractive/flask-graphql-neo4j#3]
Hey there - First of all, thanks for this! 

I keep getting the error: 
```
'Customer' object has no attribute 'select'",
```  
and I noticed that all of the `fetch()` methods attached to objects subclassing `GraphObject` within `models.py` use an undeclared method: `self.select()`. 

I cannot find the `select()` method in the declaration of `py4neo.ogm.GraphObject`, and I'm wondering if it was replaced?

**Comment by rtruxal** [comment]
`select()` appears to have changed names to `match()`, which makes a bunch of sense.

**Comment by streeck** [comment]
Hey, you're welcome, I'm glad you find this repo useful.
Indeed there was an update on py2neo to v4 over here: https://github.com/elementsinteractive/flask-graphql-neo4j/commit/b790466925bbe95c95b3da2aeab30f41b3a0a534#r33303928
Thanks for bringing this up, we indeed need to address this since the idea is to have this repo in working condition.

**Comment by streeck** [comment]
This PR #5 fixes this issue, therefore I'm closing it.
